Repository Its-Aman-Yadav/Community-Site, pull requests merged in 2024-08, with the labels that each got.

#1292 Updated Contact US
  css/style.css
  index.html
Labels: gssoc, level3

#1294 Refactored the css part of the repositonary
  about us.html
  contributor.html
  css/about us.css
  css/contact.css
  css/contributor.css
  css/feedback.css
  css/login.css
  css/ourprogram.css
  css/profile.css
  css/support.css
  feedback.html
  login.html
  our program.html
  profile.html
  support.html
Labels: gssoc, level2

#1295 Cookies modal Added
  cookie.js
  css/style.css
  index.html
Labels: gssoc, level3

#1300 feat/popup-for-goal-page-contact-form
  css/ourplan.css
  our plan.html
Labels: gssoc, level2

#1298 feat: add popup in support page
  css/support.css
  support.html
Labels: gssoc, level2

#1304 Fix FAQ Answers Visibility in Dark Mode on support.html
  support.html
Labels: gssoc, level1

#1311 fix:hover-on-testimonials
  main.css
Labels: gssoc, level1

#1309 Remove extra code from all the pages
  member.html
  network.html
  open-learning.html
  our plan.html
  our program.html
  privacypolicy.html
  support.html
Labels: gssoc, level1

#1315 Fixed Home button on Login Page
  login.html
Labels: gssoc, level1

#1317 improved cookie model ui
  cookie.js
  index.html
Labels: gssoc, level2

#1325 Made the navbar active
  index.html
Labels: gssoc, level1

#1330 tex not visible in dark mode
  css/style.css
Labels: gssoc, level1

#1333 Added Cookie pop-up
  about us.html
Labels: gssoc, level2

#1334 Fix Darkmode and User image overlapping in small size in all pages
  about us.html
  licensing.html
  member.html
  mentorship.html
  network.html
  open-learning.html
  our plan.html
  our program.html
  privacypolicy.html
  support.html
  terms&conditions.html
Labels: gssoc, level2

#1336 Feedback page Dark-mode fixed
  css/feedback.css
  feedback.html
Labels: gssoc, level2

#1340 removed contact us from main page
  index.html
Labels: gssoc, level1

#1342 Fixed Testimonials Section
  index.html
Labels: gssoc, level1

#1343 Cookie-modal made same for both pages and aligned
  about us.html
  index.html
Labels: gssoc, level2

#1345 Feat:Dark Mode Of what our Memeber say not working #1331
  index.html
  main.css
Labels: gssoc, level1

#1351 Bug Fixed About section
  index.html
Labels: gssoc, level1

#1356 Bug Fixed Cookie section
  index.html
Labels: gssoc, level3

#1357 Contact UI of support page
  css/login.css
  login.html
  support.html
Labels: gssoc, level3

#1359 Card after faqs improved
  css/style.css
  index.html
  main.css
Labels: gssoc, level2

#1363 FAQ Page improvment
  css/support.css
  support.html
Labels: gssoc, level2

#1365 Fixed Bugs
  footer/footer.js
  index.html
Labels: gssoc, level2

#1367 Bug fixed Contactus page
  contact us.html
Labels: gssoc, level1

#1369 Fixed mentorship page
  mentorship.html
Labels: gssoc, level2

#1370 Improved What we offer cards
  css/style.css
  index.html
Labels: gssoc, level3

#1371 Update login.html
  login.html
Labels: gssoc, level1

#1372 remove extra testimonial section
  index.html
Labels: gssoc, level1

#1378 Made all legal pages responsive
  licensing.html
  privacypolicy.html
  terms&conditions.html
Labels: gssoc, level3

#1381 Update our plan.html
  our plan.html
Labels: gssoc, level1

#1385 Feat : Enhanced contact section
  our plan.html
Labels: gssoc, level2

#1388 Update member.html
  member.html
Labels: gssoc, level3

#1377 Update login.html Dark mode + Responsiveness
  login.html
Labels: gssoc, level2

#1383 Updates ourplan page goals section
  our plan.html
Labels: gssoc, level2
