Repository Its-Aman-Yadav/Community-Site, pull requests merged in 2024-07, with the labels that each got.

#913 Updated nav bar
  about us.css
  about us.html
  images/project-img-2.jpeg
  images/project-img-3.jpg
  images/project-img-4.jpg
  images/project-img-5.jpg
  images/project-img-6.jpg
Labels: gssoc, level2

#917 Terms&conditions page: fixed footer alignment and UI
  index.html
  terms&conditions.html
Labels: gssoc, level3

#927 updated active links color
  css/style.css
  index.html
  index.js
Labels: gssoc, level2

#928 Contact forms, navbar bug
  css/contact-sec.css
  css/member.css
  css/ourplan.css
  member.html
  our plan.html
  support.html
Labels: gssoc, level3

#929 Added Home Button on Login Page
  login.css
  login.html
Labels: gssoc, level2

#930 Added "Scroll to top button" in only all pages
  about us.html
  index.html
  member.html
  our plan.html
  our program.html
  privacypolicy.html
  support.html
  terms&conditions.html
Labels: gssoc

#934 Added All Dedicated Pages For Texts in "Services" Section
  footer/footer.js
  mentorship.html
  network.html
  open-learning.html
Labels: gssoc, level3

#936 In small screen navbar overflow of toggle and image fix
  index.html
Labels: gssoc, level2

#926 Multiple changes (footer and navbar)
  about us.css
  css/style.css
  footer/footer.js
  index.html
  privacy.css
Labels: gssoc, level3

#947 Forgot password web page added
  Forgot_Password.html
  login.html
Labels: gssoc, level3

#954 Added Chatbot in Missing Pages
  about us.html
  member.html
  our plan.html
  our program.html
  support.html
Labels: gssoc, level2

#938 Bug Fix in Rating Star
  index.html
Labels: gssoc, level1

#944 About Page projects section improved,
  about us.css
  about us.html
Labels: gssoc, level2

#946 Update Privacy Policy Page UI
  privacypolicy.html
Labels: gssoc, level2

#959 login page updated
  login.css
  login.html
Labels: gssoc, level2

#963 Added "Licensing Page" Reflecting "MIT License" #897
  LICENSE
  footer/footer.js
  licensing.html
Labels: gssoc, level1

#948 Added "Cursor Trail Effect" to The Website
  css/style.css
  index.html
  mentorship.html
  network.html
  open-learning.html
  trail.js
Labels: gssoc, level2

#974 Licensing UI, Footer submit button
  css/style.css
  licensing.html
Labels: gssoc, level2

#977 [Feature]: change make Responsive site
  css/style.css
  index.html
Labels: gssoc, level1

#982 Fixed chatbot bug #639
  index.html
Labels: gssoc, level2

#985 ✔️Improved "Complete UI and Functionality" Of Feedback Form
  images/GIF/Feedback giphy.gif
  index.html
Labels: gssoc, level2

#993 Update index.html adding linkedin webpage link at connect with us
  index.html
Labels: gssoc, level1

#994 Add stylish scrollbars in about/member/ourprogram pages
  about us.css
  member.html
  ourprogram.css
Labels: gssoc, level2

#997 Mentorship Page complete Improvement
  icons/advice.png
  icons/balance.png
  icons/collaboration.png
  icons/leadership.png
  icons/lightbulb.png
  icons/networking.png
  icons/self-confidence.png
  icons/skill.png
  icons/technical-support.png
  mentorship.html
Labels: gssoc, level3

#1003 Bug fixed : No favicon was present in the login page
  contact us.html
  login.html
Labels: gssoc, level1

#1005 Feature : contact us in the footer directs to another page
  footer/footer.js
Labels: gssoc, level1

#1007 About page bug and edits
  about us.html
Labels: gssoc, level3

#1009 Improved ui of 6 pages
  licensing.html
  mentorship.html
  network.html
  open-learning.html
  privacypolicy.html
  terms&conditions.html
Labels: gssoc, level2

#1010 Our plan page contact improve
  our plan.html
Labels: gssoc, level2

#1012 now about us navbar working properly
  about us.html
  index.js
Labels: gssoc, level1

#1024 Network page complete improvement
  icons/advice-2.png
  icons/collaboration-2.png
  icons/line.png
  icons/opportunity.png
  icons/partners.png
  icons/social-network.png
  network.html
Labels: gssoc, level3

#1014 Improved Mode toggle
  images/moon.svg
  images/sun.svg
  index.html
Labels: gssoc, level2

#1016 improve the ui of the become a member page
  member.html
Labels: gssoc, level1

#1021 Made Open learning page title responsive
  open-learning.html
Labels: gssoc, level2

#1023 fixed the ui of the our plan page
  our plan.html
Labels: gssoc, level2

#1027 added updated logo
  images/logo1.jpeg
  images/logo2.jpeg
  images/logo_final.png
  index.html
Labels: gssoc, level1

#1028 Contact Us page improved
  contact us.html
Labels: gssoc, level2

#1030 navbar fixed
  terms&conditions.html
Labels: gssoc, level2

#1031 Navbar updated in all pages
  about us.html
  css/member.css
  css/style.css
  member.html
  our plan.html
  our program.html
  ourprogram.css
  support.html
Labels: gssoc, level3

#1035 Added Dark theme for some containers
  css/style.css
Labels: gssoc, level1

#1037 Updated about page
  about us.css
  about us.html
Labels: gssoc, level3

#1032 Add responsiveness for mobile screen stop navbar overflow in small screen contact form improvement
  css/contact-sec.css
  member.html
Labels: gssoc, level3

#1041 Forgot password
  login.html
Labels: gssoc, level1

#1047 Made Network Page Responsive
  network.html
Labels: gssoc, level3

#1061 Login Page Improvement
  login.css
  login.html
Labels: gssoc, level2

#1064 Open learning page UI update
  icons/coding-lesson.png
  icons/project.png
  icons/video.png
  icons/webinar.png
  open-learning.html
Labels: gssoc, level3

#1049 licensing navbar fixed
  licensing.html
Labels: gssoc, level2

#1054 made the contact us page responsive
  contact us.html
Labels: gssoc, level2

#1057 make the terms and conditions page responsive
  terms&conditions.html
Labels: gssoc, level1

#1063 fixed the cursor trail bug in the our plan and our program page
  our plan.html
  our program.html
Labels: gssoc, level1

#1073 Added Pop up modal for login/register
  index.html
Labels: gssoc, level3

#1050 fixed the login page
  login.css
Labels: gssoc, level1

#1067 Added home button in login page
  login.css
  login.html
Labels: gssoc, level2

#1068 Added nav-menu for mobile screen
  index.html
Labels: gssoc, level2

#1074 added dark mode for about us and fixed navbar issue
  about us.css
  about us.html
Labels: gssoc, level3

#1071 i have fixed the trail bug in all the pages
  licensing.html
  member.html
  privacypolicy.html
  support.html
  terms&conditions.html
Labels: gssoc, level1

#1075 improved ui of the login pop up and made it responsive
  index.html
Labels: gssoc, level2

#1100 Modal UI updated
  index.html
Labels: gssoc, level3

#1098 NavBar Links updated & Footer text bug fixed
  about us.html
  footer/footer.js
  mentorship.html
  network.html
  open-learning.html
  our plan.html
  privacypolicy.html
Labels: gssoc, level3

#1079 terms and conditions update
  terms&conditions.html
Labels: gssoc, level2

#1084 ✔️Improved "Support" Page in the Footer!
  support.css
  support.html
Labels: gssoc, level3

#1085 Fixed text in light and dark mode in contact form
  css/style.css
  index.html
Labels: gssoc, level2

#1088 dark mode in network page
  network.html
Labels: gssoc, level2

#1099 Edit in spacing and grammar
  index.html
Labels: gssoc, level1

#1089 Enhanced register successfully and login successfully
  login.html
Labels: gssoc, level3

#1090 addeed the linkedin profile link in the login page
  login.html
Labels: gssoc, level1

#1097 Support Page Improvement
  support.css
  support.html
Labels: gssoc, level2

#1102 dark mode in licensing page
  licensing.html
Labels: gssoc, level1

#1104 Added dark mode in open learning webpage
  open-learning.html
Labels: gssoc, level1

#1106 add dark mode feature in mentorship page
  mentorship.html
Labels: gssoc, level1

#1125 Our plan Dark-mode fixed
  css/ourplan.css
  our plan.html
Labels: gssoc, level3

#1127 Added dark mode for support page
  support.css
  support.html
Labels: gssoc, level2

#1122 Added dark mode for terms&conditions and privacypolicy pages
  privacy.css
  privacypolicy.html
  terms&conditions.html
Labels: gssoc, level2

#1110 BUG: Dark Mode Button Not Responsive
  index.html
Labels: gssoc, level1

#1112 Added footer theme
  css/style.css
  footer/footer.js
Labels: gssoc, level2

#1115 Fix visibility of icons in Navigation Bar for Dark Mode
  css/style.css
Labels: gssoc, level1

#1119 popup fr correct and wrong email id
  footer/footer.js
Labels: gssoc, level2

#1121 Fixes social media icons
  index.html
Labels: gssoc, level2

#1137 Update index.html
  index.html
Labels: gssoc, level1

#1117 Fix: Correct Positioning of Dark Mode Toggle
  index.html
Labels: gssoc, level1

#1128 Privacy Policy and Network Page Improvement
  network.html
  privacy.css
  privacypolicy.html
Labels: gssoc, level3

#1134 Our program dark mode
  css/style.css
  our program.html
  ourprogram.css
Labels: gssoc, level3

#1136 Feat: Added dark mode in support page
  support.css
  support.html
Labels: gssoc, level2

#1138 Added dark mode toggle button & implemented dark mode for contact us
  contact us.html
  contact.css
Labels: gssoc, level3

#1140 Improve UI of get in touch form
  support.html
Labels: gssoc, level2

#1141 incorrect input fields for email and password
  signup.html
Labels: gssoc, level1

#1144 Added dark mode in become a member page
  member.html
  support.html
Labels: gssoc, level1

#1157 dark mode feature in contact us page
  contact us.html
Labels: gssoc, level2

#1152 Added Contributor's Page
  contributor.css
  contributor.html
  contributor.js
  css/style.css
  footer/footer.js
Labels: gssoc, level3

#1160 Made Testimonials responsive
  css/style.css
  index.html
Labels: gssoc, level2

#1162 Mentorship and our plan page improvement
  mentorship.html
  our plan.html
Labels: gssoc, level2

#1165 feat: popup display message we will connect you soon in member contact page
  css/member.css
  member.html
Labels: gssoc, level2

#1173 UI improvement
  contact us.html
  contact.css
Labels: gssoc, level1

#1176 fixed scroll bug
  contributor.js
Labels: gssoc, level1

#1179 Contact us page
  contact us.html
Labels: gssoc, level3

#1183 fixed major bug in all the pages
  about us.html
  licensing.html
  member.html
  mentorship.html
  network.html
  open-learning.html
  our plan.html
  privacypolicy.html
  support.html
  terms&conditions.html
Labels: gssoc, level2

#1190 updated navbar, fix the UI of about section added bit transition effect and fixed the reviews and testimonials section
  css/style.css
  feedback.html
  footer/footer.js
  index.html
  index.js
  main.css
Labels: gssoc, level3

#1159 Update login.html
  login.html
Labels: gssoc, level1

#1191 Fixed All CSS bugs, restored the Website
  css/style.css
Labels: gssoc, level3

#1197 added toggle button & dark theme for feedback
  feedback.css
  feedback.html
Labels: gssoc, level2

#1199 Contributor Stylish page
  contributor.css
  contributor.html
Labels: gssoc, level3

#1200 Contributor page improvement and background change in feedback page
  contributor.html
  feedback.html
Labels: gssoc, level2

#1205 Improved Visibility of Text in Services Section for Dark Mode
  css/style.css
Labels: gssoc, level1

#1209 BUG : Footer fixed
  footer/footer.js
Labels: gssoc, level1

#1210 New and Improved Contact Form UI in Member.html!
  member.html
Labels: gssoc, level2

#1212 Support Bug Fix
  support.html
Labels: gssoc, level2

#1215 Contact Us page UI to match website theme
  contactUs_img.png
  our plan.html
Labels: gssoc, level2

#1221 feat: Feedback Page Improved
  feedback.css
  feedback.html
  feedback_old.html
Labels: gssoc, level3

#1223 Added Contact Us Form Feature
  css/style.css
  index.html
Labels: gssoc, level2

#1224 Removed extra BG
  index.html
Labels: gssoc, level1

#1226 linked contact us page to navbar contact
  index.html
Labels: gssoc, level2

#1228 feat: add popup for cntact us and give some gap in social icons
  contact us.html
Labels: gssoc, level2

#1230 feat: add dark mode in contributor page
  contributor.css
  contributor.html
Labels: gssoc, level2

#1232 Fix Scroll to top and navbar overlapping
  network.html
Labels: gssoc, level1

#1233 Bug: Fixed Footer
  footer/footer.js
Labels: gssoc, level2

#1240 Improved Styling of Homepage by editing card height in testimonials section and color of trailing cursor.
  css/style.css
  main.css
  trail.js
Labels: gssoc, level2

#1235 added scroll animation for our plan and member page
  css/member.css
  member.html
  our plan.html
Labels: gssoc, level3

#1237 Support page UI
  images/faq.png
  support.css
  support.html
Labels: gssoc, level3

#1249 feat: add dark mode in feedback page
  feedback.css
Labels: gssoc, level2

#1247 Navbar Bugs solved
  about us.html
  contributor.html
  css/member.css
  css/ourplan.css
  index.html
  main.css
  member.html
  mentorship.html
  network.html
  open-learning.html
  our plan.html
  our program.html
  privacypolicy.html
  support.css
  support.html
  terms&conditions.html
Labels: gssoc, level3

#1244 Contact Us of member page UI
  member.html
Labels: gssoc, level2

#1250 Mentorship Page bugs fixed
  mentorship.html
Labels: gssoc, level3

#1258 Restored Counter on Index page
  css/style.css
  index.html
  main.css
Labels: gssoc, level2

#1260 About section improved
  css/style.css
  index.html
Labels: gssoc, level3

#1265 added linkedin page at login page
  login.html
Labels: gssoc, level1

#1266 Contact Us page UI
  contact us.html
Labels: gssoc, level3

#1270 Support UI improvement
  support.css
  support.html
Labels: gssoc, level2

#1272 Full Profile page improvement(Made it responsive in all the devices and improved the background)
  profile.css
  profile.html
Labels: gssoc, level3

#1273 Home page UI Edits/ BUGs fix
  css/style.css
  index.html
Labels: gssoc, level2

#1275 Login Modal Dark Mode added
  main.css
Labels: gssoc, level2

#1277 Legal pages dark mode
  licensing.html
  privacy.css
  privacypolicy.html
  terms&conditions.html
Labels: gssoc, level2

#1280 Membership Page Bugs and UI edits
  css/member.css
  member.html
Labels: gssoc, level3

#1284 Feedbaack Page
  feedback.css
  feedback.html
Labels: gssoc, level3

#1286 ✔️Improved Complete UI and Functionality of Popup Modal!
  index.html
Labels: gssoc, level2

#1288 ✔️Added Diagonal Hovering Effect to Each Card!
  contributor.css
Labels: gssoc, level2
