Repository Its-Aman-Yadav/Community-Site, pull requests merged in 2024-06, with the labels that each got.

#503 added the most requested FAQs
  index.html
Labels: gssoc, level1

#504 modify UI design of contact page
  index.html
Labels: gssoc, level2

#505 Navigation bar Css fixed; Added Hover effect; Font sizes of various headings fixed; Feedback section added and hyperlinked
  css/style.css
  index.html
Labels: gssoc, level3

#508 contact page enhanced
  css/style.css
  index.html
Labels: gssoc, level1

#523 about section
  css/style.css
  index.html
Labels: gssoc, level2

#531 Feeback form working
  index.html
Labels: gssoc, level1

#534 Navbar Improved
  css/style.css
  index.html
  index.js
Labels: gssoc, level2

#538 Updated testimonials section #181
  css/style.css
  images/img-1.jpg
  images/img-2.jpg
  images/img-3.jpg
  images/img-4.jpg
  images/img-5.jpg
  images/img-6.jpg
  index.html
Labels: gssoc, level2

#540 Interface improved; Input Text visible; Join Discord button centered; Message popup seperated for contact and feedback; Feedback sec background added
  css/style.css
  index.html
Labels: gssoc, level3

#547 Added styles to buttons and added hovering effect #463
  index.html
Labels: gssoc, level1

#557 1. Contact form and feedback form added; 2. Footer links added; 3. Testimonial images visible now;4. Duplicate testimonial removed added in one; 5. Website title logo added; 6. Problem in HTML code fixed
  css/style.css
  index.html
Labels: gssoc, level3

#552 Changed Footer
  css/style.css
  index.html
Labels: gssoc, level3

#553 syntax issues sorted
  index.html
Labels: gssoc, level1

#554 Fix: Resolved contact form issues and enhanced UI
  contact us.html
  css/style.css
  index.html
Labels: gssoc, level2

#567 [FIX]: Removed unnecessary text below navbar
  index.html
Labels: gssoc, level1

#570 added left and right scrolling to testimonials
  css/style.css
  css/swiper-bundle.min.css
  index.html
  index.js
  js/swiper-bundle.min.js
Labels: gssoc, level2

#380 I have added more FAQs
  index.html
Labels: GSSoC 24, gssoc, level1

#581 input size and box color
  contact us.html
Labels: gssoc, level1

#585 Footer alignment and quicklinks addition
  css/style.css
  index.html
Labels: gssoc, level2

#594 Enhancements: Improved email validation and error handling + Readme updatd ☀️
  README.md
  index.js
Labels: gssoc, level2

#595 Multiple issues fixed : Testimonial buttons working, Duplicate sections removed; CSS of About Us, Contact, Member, Our plan and Our program (5 webpages) fixed
  about us.html
  contact us.html
  css/style.css
  index.html
  member.html
  our plan.html
  our program.html
  support.html
Labels: gssoc, level3

#596 Added login / register page
  index.html
  login.css
  login.html
Labels: gssoc, level3

#606 Fixed Issue #593 - Service card of same size now; Feedback, Contact Section Improved; HTML code fixed; Problem in FAQ section solved; Testimonial images added
  css/style.css
  index.html
Labels: gssoc, level3

#608 Navbar CSS fixed
  css/style.css
  index.html
Labels: gssoc, level3

#612 added navbar to about
  about us.css
  about us.html
  css/style.css
Labels: gssoc, level3

#617 Fixed bug #615 - Resolved the overflow of text in the cards of FAQ section and added fifth star in the third card
  index.html
Labels: gssoc, level1

#631 fix : Footer fixed
  css/style.css
Labels: gssoc, level1

#632 Testimonial's Photos make visible
  index.html
Labels: gssoc, level2

#642 Addition of same footer to all pages
  about us.css
  about us.html
  css/style.css
  footer/footer.js
  index.html
  member.html
  our plan.html
  our program.html
  support.html
Labels: gssoc, level2

#658 changed the UI of Form backgrounds
  css/style.css
  index.html
Labels: gssoc, level2

#659 Fixed scroll function JS
  index.html
Labels: gssoc, level1

#660 Made changes to about us page and enhanced nav bar
  about us.css
  about us.html
  css/style.css
  footer/footer.js
  images/community.jpeg
  images/community.png
Labels: gssoc, level2

#652 Enhanced the FAQs section
  css/style.css
  index.html
Labels: gssoc, level2

#654 Fixed #644 - Corrected the alignment of placeholder in Feedback section
  index.html
Labels: gssoc, level1

#664 changed content alignment
  index.html
  our program.html
Labels: gssoc, level3

#667 Issue #528: Redesigned Scroll-to-Top Button with Progress Indicator
  css/style.css
  index.html
Labels: gssoc, level2

#671 Footer Alignment and Responsive on mobile
  css/style.css
  footer/footer.js
Labels: gssoc, level1

#680 Update README.md
  README.md
Labels: gssoc, level1

#683 fixed the testimonial section
  css/style.css
  index.html
Labels: gssoc, level1

#682 Contact and Feedback form Redesign
  css/style.css
  index.html
Labels: gssoc, level2

#692 Fixing multiple sections
  css/style.css
  index.html
Labels: gssoc, level2

#698 addition of navbar to plan page
  our plan.html
Labels: gssoc, level1

#707 Fixed: Spacing, and added HR in footer
  css/style.css
  footer/footer.js
Labels: gssoc, level2

#713 LinkedIn Handler is added [ Update footer.js ]
  footer/footer.js
Labels: gssoc, level1

#714 Issue No. = #670 Now, signup page working properly, Issue No.= #669 Now, login page working properly ,Issue no.=#624 now ,email accepting valid input
  login.html
  signup.html
Labels: gssoc, level3

#718 Feat: Login/sign up page, with google added
  login.css
  login.html
  signup.html
Labels: gssoc, level3

#734 Scrollbar updated
  index.html
Labels: gssoc, level1

#741 Fixed issue #725
  footer/footer.js
Labels: gssoc, level2

#746 Added dark mode feature #637
  css/style.css
  index.html
Labels: gssoc, level2

#751 Stylish Scrollbar with hover effects
  index.html
Labels: gssoc, level1

#752 Alignment issue resolved
  css/style.css
Labels: gssoc, level1

#753 Header hover effect margins and paddings Fixed alongwith new icons
  css/style.css
  index.html
Labels: gssoc, level1

#602 Made the text visible #549
  css/style.css
  index.html
Labels: gssoc, level2

#756 [Feat]: Program page UI
  our program.html
  ourprogram.css
Labels: gssoc, level2

#758 Landing Page UI improved
  css/style.css
  index.html
Labels: gssoc, level1

#766 [Issue no = #748] Added the whatsapp icon and email icon to the join the community in footer section
  footer/footer.js
  index.html
  login.html
  member.html
  our plan.html
  our program.html
  support.html
Labels: gssoc, level1

#769 "Confirm Password" field added in signup page
  signup.html
Labels: gssoc, level1

#773 changed about page
  about us.css
  about us.html
  images/about-img (2).png
Labels: gssoc, level2

#774 Improved Login page UI with Animations
  index.html
  login.css
  login.html
  signup.html
Labels: gssoc, level2

#776 [ISSUE No . = #460 ] ,Submit button is now fully visible in become a member section
  css/style.css
  member.html
Labels: gssoc, level1

#783 Enhanced feedback and get in touch form UI
  css/style.css
Labels: gssoc, level1

#784 Social Icons hover effects added
  css/style.css
  footer/footer.js
Labels: gssoc, level1

#785 Fixed Footer UI
  css/style.css
  index.html
Labels: gssoc, level1

#786 Twiiter latest icon updated
  footer/footer.js
Labels: gssoc, level1

#788 Updated FAQ UI
  css/style.css
Labels: gssoc, level1

#789 updated login/signup page #640
  image.gif
  login.css
  login.html
Labels: gssoc, level3

#793 Member page modifed
  css/member.css
  images/contact-form.png
  images/registration.png
  images/stopwatch.png
  images/team.png
  member.html
Labels: gssoc, level3

#806 Removed Unnecessary Text
  index.html
Labels: gssoc, level1

#809 Added toggle eye functionality in login and register page
  login.css
  login.html
Labels: gssoc, level2

#810 Added Emojis instead of Stars
  index.html
Labels: gssoc, level2

#811 website logo title fixed, faq section, and contact-feedback section.
  css/style.css
  index.html
  index.js
Labels: gssoc, level2

#814 About Section Responsiveness added
  css/style.css
Labels: gssoc, level2

#815 Removed Collsion between Navbar and Text
  index.html
Labels: gssoc, level1

#816 Added Toastify Message
  index.html
Labels: gssoc, level3

#820 Card UI improved
  css/style.css
  index.html
Labels: gssoc, level2

#822 Navbar fixed
  css/style.css
  index.html
Labels: gssoc, level2

#833 Removed Two Feedback forms
  index.html
Labels: gssoc, level1

#834 width fixed for toggle button
  css/style.css
Labels: gssoc, level1

#835 Fixed Password special character validation issue using alert method #812
  login.html
Labels: gssoc, level1

#838 navbar updated for support page
  support.html
Labels: gssoc, level1

#472 Made changes in the service section
  css/style.css
  index.html
Labels: gssoc, level1

#846 About toastify message
  index.html
Labels: gssoc, level2

#849 appropriate meta tags are added to website for making SEO friendly
  index.html
Labels: gssoc, level1

#851 Feedback Form UI/UX Fixed
  css/style.css
  index.html
Labels: gssoc, level3

#854 updated about us page
  about us.css
  about us.html
  images/who.png.png
Labels: gssoc, level1

#861 Navbar Edits
  css/style.css
  index.html
Labels: gssoc, level2

#867 Our plan page improved
  css/ourplan.css
  our plan.html
Labels: gssoc, level3

#870 Support page UI improved
  support.css
  support.html
Labels: gssoc, level3

#874 added scroll activated number counter
  about us.css
  about us.html
  index.js
Labels: gssoc, level3

#877 FAQS section improved
  css/style.css
  index.html
Labels: gssoc, level2

#878 Feedback section improved
  css/style.css
  index.html
Labels: gssoc, level2

#880 Fixed UI of contact form and incorporated a backend structure
  index.html
Labels: gssoc, level1

#882 Resolved Dark Mode Persist Issue
  index.html
Labels: gssoc, level2

#884 updated discord btn
  index.html
Labels: gssoc, level1

#886 Created a timeline on how to join us
  about us.css
  about us.html
  images/project-img-1.jpg
Labels: gssoc, level3

#890 Added a Forgot password page redirecting from login.html file issue no - #845
  Forgot_Passwd.css
  Forgot_Password.html
  login.html
Labels: gssoc, level3

#893 Contact form improved
  css/style.css
  index.html
Labels: gssoc, level2

#892 Login Form UI update
  login.css
  login.html
Labels: gssoc, level2

#896 Multiple edits on About Page
  about us.css
  about us.html
  css/style.css
Labels: gssoc, level3

#903 Color on hover added according to their logo
  footer/footer.js
Labels: gssoc, level1
