Repository Its-Aman-Yadav/Community-Site, pull requests merged in 2024-10, with the labels that each got.

#1412 updated the profile menu css
  css/animate.min.css
  css/bootstrap.min.css
  css/profile.css
  profile.html
Labels: gssoc, level1

#1413 change color of text in placeholder
  contact us.html
Labels: gssoc, level1

#1419 In Contact Us width of input section solved
  contact us.html
Labels: gssoc, level1

#1420 Centering the Get In Touch card in the Contact Us Container
  contact us.html
Labels: gssoc, level1

#1438 Update index.html
  index.html
Labels: gssoc, level1

#1450 hover change
  css/profile.css
Labels: gssoc, level1

#1455 changes index.html
  index.html
Labels: gssoc, level1

#1458 Added media queries and made it compatile for small devices
  css/login.css
  login.html
Labels: level1, gssoc-extd, hactoberfest-accepted

#1461 made what we offer section responsive #1460 solved
  index.html
Labels: level1, gssoc-extd, hactoberfest-accepted

#1467 hover updated
  css/profile.css
Labels: level1, gssoc-extd, hactoberfest-accepted

#1469 dark mode in FAQ fix
  css/style.css
Labels: level1, gssoc-extd, hactoberfest-accepted

#1471 twitter logo fix
  contact us.html
Labels: level1, gssoc-extd, hactoberfest-accepted

#1480 Added chatbot profile icon
  index.html
  script.js
Labels: level2, gssoc-extd, hactoberfest-accepted

#1489 added Auth using mongo node and express [backend]
  backend/.gitignore
  backend/app.js
  backend/config/databaseConfig.js
  backend/controller/authController.js
  backend/index.js
  backend/middleware/jwtAuth.js
  backend/model/userSchema.js
  backend/package-lock.json
  backend/package.json
  backend/router/authRoute.js
Labels: level3, gssoc-extd, hactoberfest-accepted

#1490 sucessfully attached the footer section of the
  contact us.html
Labels: level3, gssoc-extd, hactoberfest-accepted

#1500 Fix: Contact number validation to accept exactly 10 digits
  contact us.html
Labels: level2, gssoc-extnd, hactoberfest-accepted

#1502 Feat:[UI/UX] fix design , styling of Contact Page #1501
  contact us.html
  css/style.css
  footer/footer.js
  index.html
Labels: level3, gssoc-extd, hactoberfest-accepted
