Repository Its-Aman-Yadav/Community-Site, pull requests merged in 2024-05, with the labels that each got.

#10 changed the border in contact form
  css/style.css
Labels: GSSoC 24

#50 Added Discord icon on the link
  css/style.css
  index.html
Labels: GSSoC 24

#47 Update README.md
  README.md
Labels: GSSoC 24

#43 feat: added issue btns and respective forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc, level 2

#32 Update of CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: gssoc, level 1

#31 form updated
  index.html
Labels: gssoc, level 1

#23 #Updated the Mountains image in the hero section #7
  images/Slide1.jpg
  images/Slide2.jpg
  js/custom.js
Labels: gssoc, level 1

#54 [ Feature ] Make the Form Section work #9
  index.html
Labels: gssoc, level 3

#106 Gssoc level1 princy issue#94
  index.html
  package-lock.json
  package.json
Labels: gssoc, level 1

#100 Feat/updation-for-bold-cards
  css/style.css
  index.html
Labels: gssoc, level 2

#103 Changed Font style and size along with some alignments.
  css/style.css
  index.html
Labels: gssoc, level 1

#102 fixing box size of message and adding visible border
  css/style.css
  index.html
Labels: gssoc, level 1

#130 Added testimonials
  css/style.css
  images/testi_1.jpg
  images/testi_2.jpeg
  images/testi_3.jpeg
  index.html
Labels: gssoc, level 2

#141 Added cards for presenting information in a clear and concise way
  .vscode/settings.json
  css/style.css
  index.html
Labels: gssoc, level 2

#191 Fixed issue #170
  index.html
Labels: gssoc, level 1

#202 Created responsive navbar and added logo in it.
  css/style.css
  index.html
Labels: gssoc, level 2

#196 finally so;lved # issue 11
  index.html
Labels: gssoc, level 3

#209 Fixed issue #208
  index.html
Labels: gssoc, level 1

#212 Updated index.html and style.css
  css/style.css
  index.html
Labels: gssoc, level 1

#215 Fixed the navigation bar issue #210; It is now clickable; responsive, also sticky throughout the website
  css/style.css
  fav.png
  index.html
Labels: gssoc, level 2

#216 Hovering effect on nav bar solved
  css/style.css
  index.html
Labels: gssoc, level 1

#218 Update copyright year to dynamically display the current year
  index.html
Labels: gssoc, level 1

#231 Added hovering effect to page #147 resolved
  css/style.css
Labels: gssoc, level 1

#230 Create learn.md
  learn.md
Labels: gssoc, level 1

#229 Extra submit button removed
  index.html
Labels: gssoc, level 1

#237 Enhanced and updated the services page #207
  css/style.css
  index.html
Labels: gssoc, level 2

#242 faq section updated
  css/style.css
  index.html
  js/custom.js
Labels: gssoc, level 2

#250 feat: Added icons to the navbar
  css/style.css
  index.html
Labels: gssoc, level 1

#248 Have improved the UI and UX for the Home Buttons
  css/style.css
  index.html
Labels: gssoc, level 1

#253 fix: Fixed inconsistent text and remove extra padding in the home buttons
  css/style.css
  index.html
Labels: gssoc, level1

#241 Updated navbar
  index.html
Labels: gssoc, level1

#190 Added a new user experience section
  css/style.css
  images/profile1.jpg
  images/profile2.jpg
  images/profile3.jpg
  index.html
Labels: gssoc, level2

#193 Updated images to slideshow #128
  css/style.css
  images/Slide3.jpg
  images/Slide4.jpg
  images/Slide5.jpg
  images/Slide6.jpg
  images/getInTouch.png
  index.html
  js/custom.js
Labels: gssoc, level1

#236 Fix issue #219: Flex boxs and Footer is Fixed by @nileshsn
  css/style.css
  index.html
Labels: gssoc, level2

#263 Fixed Get In Touch Button issue | #245
  css/style.css
Labels: gssoc, level1

#264 Fixed border radius and extra padding issue #245
  css/style.css
  index.html
Labels: gssoc, level1

#267 Smooth Transition effect on back-top added.
  css/style.css
  index.html
  js/smoothscroll.js
Labels: gssoc, level2

#286 The changes: Navbar orientation fixed; FAQs section added in Navbar; Hello Villager colour visible now
  css/style.css
  index.html
Labels: gssoc, level3

#277 updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc, level1

#289 change Discord ,Linkedin styling and front page appearance
  css/style.css
  index.html
Labels: GSSoC 24, level2

#305 Fixed typography errors in many areas of the website
  css/style.css
  index.html
Labels: GSSoC 24, level2

#316 Issue 315 solved
  index.html
Labels: gssoc, level1

#313 [FIX]: Fixed the responsiveness
  css/style.css
  index.html
Labels: gssoc, level1

#325 Fixed issue #320 and #321 :The Service card content fit well now; navigation bar position changes fixed #322
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/greetings.yml
  .gitignore
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CURSOR1.png
  about us.html
  contact us.html
  css/style.css
  fav.png
  images/Slide1.jpg
  images/Slide2.jpg
  images/Slide3.jpg
  images/Slide4.jpg
  images/Slide5.jpg
  images/Slide6.jpg
  images/getInTouch.png
  images/profile1.jpg
  images/profile2.jpg
  images/profile3.jpg
  images/testi_1.jpg
  images/testi_2.jpeg
  images/testi_3.jpeg
  index.html
  index.js
  js/custom.js
  js/smoothscroll.js
  learn.md
  member.html
  our plan.html
  our program.html
  package-lock.json
  package.json
  support.html
Labels: gssoc, level3

#311 Added subscribe form In the footer section
  css/style.css
  index.html
  index.js
Labels: gssoc, level1

#300 Fixed Alignment issues in Footer Section
  css/style.css
Labels: gssoc, level1

#310 Updated the Community links to icons
  README.md
Labels: gssoc, level1

#319 Created a feedback section
  feedback.css
  feedback.html
  feedback.js
  index.html
Labels: gssoc, level2

#349 Footer's email placeholder issue fixed
  css/style.css
Labels: gssoc, level1

#371 Attached links to the components in footer
  .vscode/settings.json
  index.html
Labels: gssoc, level1

#382 Updated JOIN DISCORD button
  css/style.css
Labels: gssoc, level1

#387 Fixed issue #365 and #386; Home page look fixed and navigation bar looks Fixed; "Join Discord" and "Join LinkedIn" now visible; Nav bar multiple issues fixed
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/greetings.yml
  .gitignore
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CURSOR1.png
  README.md
  about us.html
  contact us.html
  css/style.css
  fav.png
  images/Slide1.jpg
  images/Slide2.jpg
  images/Slide3.jpg
  images/Slide4.jpg
  images/Slide5.jpg
  images/Slide6.jpg
  images/getInTouch.png
  images/profile1.jpg
  images/profile2.jpg
  images/profile3.jpg
  images/testi_1.jpg
  images/testi_2.jpeg
  images/testi_3.jpeg
  index.html
  index.js
  js/custom.js
  js/smoothscroll.js
  learn.md
  member.html
  our plan.html
  our program.html
  package-lock.json
  package.json
  support.html
Labels: gssoc, level3

#390 Recreated Navbar, Improved readability of home screen content, Added Hamburger button
  css/style.css
  index.html
Labels: gssoc, level2

#396 'Get in Touch' Section can be improved #352
  index.html
Labels: gssoc, level1

#400 Text visible for discord and linkedIn buttons
  index.html
Labels: gssoc, level1

#405 Chatbot integrated #306
  css/style.css
  index.html
Labels: gssoc, level3

#398 Resolved Service-section #350
  css/style.css
Labels: gssoc, level1

#406 Happyrao
  index.html
Labels: gssoc, level3

#411 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: gssoc, level3

#416 updated and resolved navbar conflict #304 #356
  .vscode/settings.json
  css/style.css
  index.html
Labels: gssoc, level3

#432 update quick links
  css/style.css
  images/aboutimgslide1.jpg
  index.html
Labels: gssoc, level1

#412 submit is centered in all the screens also make the nav bar visible responsively for both mobile and large screens
  index.html
Labels: gssoc, level2

#437 Added discord logo beside JOIN Discord btn
  index.html
Labels: gssoc, level1

#440 Removed the scroll to top feature
  css/style.css
  index.html
Labels: gssoc, level2

#451 Enhance Footer with Additional Navigation Links
  index.html
Labels: gssoc, level1

#455 Email validation in subscribe form
  css/style.css
  index.html
  index.js
Labels: gssoc, level2

#464 Fixed issue #431
  css/style.css
  index.html
Labels: gssoc, level1

#471 Updated styles for contact form and made it attractive and modern
  index.html
Labels: gssoc, level2

#475 Added smooth transition effect in the homepage
  index.html
Labels: gssoc, level1

#476 Updated Cursor
  css/style.css
  images/cursor.png
Labels: gssoc, level1

#479 Responsive Modern Navigation Bar #378
  css/style.css
  index.html
Labels: gssoc, level2

#499 Implemented a check on message length
  index.html
Labels: gssoc, level1
